### ISSUE TITLE
Make $help more useable.

### ISSUE THREAD

**Issue by Tainmere** [buosseph/edmp-bot#11]
Issue: Right now $help spawns a huge wall of text. 

Possible solution:
It could be improved by having $help showing a list of categories (eg feedback, users or others), then using $help <ID> or $help <Category> gives you the specific commands aviable for that particular category.
Would be particulary helpful in #feedback-trade if people can just type $help feedback and they get the commands used in the feedback system.
COuld be combined with the bot DMing you the list of commands, like $getFeedback.

**Comment by admiralbumblebee** [comment]
Feature added.
