### ISSUE TITLE
Logger outputs edit message to logs channel whenever message embeds resolve.

### ISSUE THREAD

**Issue by b4shful** [buosseph/edmp-bot#27]
The messageUpdate event seems to be emitted when a message is pinned or the embeds resolve. This gives edit messages in the logs-general channel with the exact same content on the B: and A: section. Examples of this happening would be when most links are posted, when the embed loads with preview information, the message is shown as edited in the log.

Example: Link to my website, after 2 seconds the embed pops up below
![image](https://user-images.githubusercontent.com/28313200/52903127-4b429b80-3211-11e9-90e7-6525603d6047.png)

This then gets logged as a message edit by the bot
![image](https://user-images.githubusercontent.com/28313200/52903132-5e556b80-3211-11e9-9986-538a46a0baa7.png)

This could possibly be fixed by adding more conditions such as a check to see if a real edit was made, or if it was just a pin/embed resolving. Differentiating between these would also allow you to check if a message was pinned.

**Comment by buosseph** [comment]
Adding a check for the [pinned](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=pinned) property in the message received during `messsageUpdate` will fix this.
